image: microsoft/dotnet:2.2-sdk

stages:
    - build
    - deploy

before_script:
    - cd \MEE7-Discord-Bot
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

deploy:
    stage: deploy
    script: 
        - "dotnet run"
