stages:
    - build
    - deploy

before_script:
    - cd ./MEE7-Discord-Bot

build:
    stage: build
    script:
        - docker build -t MEEIMAGE -f Dockerfile .

deploy:
    stage: deploy
    script: 
        - docker run -it --rm MEEIMAGE
