stages:
    - deploy

deploy:
    image:
        name: docker/compose:1.24.1
        entrypoint: ["/bin/sh", "-c"]
    stage: deploy
    script: 
        - docker-compose build
        - BotToken=$BOT_TOKEN docker-compose up -d
