stages:
    - build
    - deploy

before_script:
    - cd \MEE7-Discord-Bot
    - dotnet restore

build:
    stage: build
    script:
        - dotnet build
    artifacts:
        paths:
            - ./

deploy:
    stage: deploy
    script: 
        - dotnet run
