stages:
    - build
    - deploy

before_script:
    - cd ./MEE7-Discord-Bot

build:
    stage: build
    script:
        - dotnet build -c Release
    artifacts:
        paths:
            - ./MEE7-Discord-Bot/bin/

deploy:
    stage: deploy
    script: 
        - dotnet run -c Release
