version: '3.4'

services:
  mee7-discord-bot:
    image: ${DOCKER_REGISTRY-}mee7discordbot
    build:
      context: .
      dockerfile: MEE7-Discord-Bot/Dockerfile
    restart: on-failure
    environment:
      - BotToken
      - access_token
      - access_token_secret
      - customer_key
      - customer_key_secret
      - CI_SERVER