image: microsoft/dotnet:2.2-sdk

stages:
    - build
    - test

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "dotnet run"
