name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Push
        env:
          push: ${{ secrets.LOUIS_PUSH }}
        run: | 
          git pull https://$push@git.bre4k3r.de/dev-bre4k3r/Discord-Bot
          git push https://$push@git.bre4k3r.de/dev-bre4k3r/Discord-Bot
